# Generated by Django 5.0.3 on 2024-04-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evénement',
            old_name='titre',
            new_name='nom_evnt',
        ),
        migrations.RemoveField(
            model_name='evénement',
            name='date',
        ),
        migrations.RemoveField(
            model_name='evénement',
            name='lieu',
        ),
        migrations.AddField(
            model_name='evénement',
            name='addresse',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='evénement',
            name='date_debut_enchere',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='evénement',
            name='date_debut_evnt',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='evénement',
            name='date_debut_soumission',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='evénement',
            name='date_fin_enchere',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='evénement',
            name='date_fin_evnt',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='evénement',
            name='date_fin_soumission',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='evénement',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='evénement',
            name='pays',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='evénement',
            name='ville',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
