# Generated by Django 5.0.3 on 2024-04-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_evénement_heure_debut_soumission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evénement',
            old_name='heuree_debut_enchere',
            new_name='heure_debut_enchere',
        ),
    ]
