# Generated by Django 5.0.3 on 2024-05-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_heuree_debut_enchere_evénement_heure_debut_enchere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evénement',
            name='date_debut_enchere',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evénement',
            name='date_debut_soumission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evénement',
            name='date_fin_enchere',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evénement',
            name='date_fin_soumission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evénement',
            name='heure_debut_enchere',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evénement',
            name='heure_debut_soumission',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evénement',
            name='heure_fin_enchere',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evénement',
            name='heure_fin_soumission',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
