# Generated by Django 5.0.3 on 2024-05-13 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_soumission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoAuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_co_auteur', models.EmailField(max_length=254)),
                ('soumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.soumission')),
            ],
        ),
    ]
