# Generated by Django 5.0.3 on 2024-05-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_evaluation_maitrise_alter_evaluation_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='soumission',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='soumission',
            name='attestation',
            field=models.FileField(upload_to='documents/', verbose_name='Attestation'),
        ),
        migrations.AlterField(
            model_name='soumission',
            name='contrat',
            field=models.FileField(upload_to='documents/', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='soumission',
            name='prestation',
            field=models.FileField(upload_to='documents/', verbose_name='Presentation'),
        ),
    ]
