# Generated by Django 5.0.3 on 2024-05-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='email_invitation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
