# Generated by Django 5.0.3 on 2024-05-17 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_affectation'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='evenement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.evénement'),
        ),
    ]
