# Generated by Django 5.0.3 on 2024-05-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_remove_affectation_evenement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soumission',
            name='evenement',
        ),
    ]
