# Generated by Django 5.0.3 on 2024-05-18 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_remove_soumission_evenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='soumission',
            name='evenement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.evénement'),
        ),
    ]
