# Generated by Django 5.0.3 on 2024-05-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_remove_evaluation_evenement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(blank=True, choices=[('evaluateur', 'evaluateur'), ('speaker', 'speaker'), ('editeur', 'editeur')], max_length=30, null=True),
        ),
    ]
