# Generated by Django 5.0.3 on 2024-05-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_alter_invitation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='coauteur',
            name='nom_coauteur',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coauteur',
            name='prenom_coauteur',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
