# Generated by Django 5.0.3 on 2024-05-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_encheres'),
    ]

    operations = [
        migrations.AddField(
            model_name='encheres',
            name='enthousiasme',
            field=models.CharField(blank=True, choices=[('Je peux', 'Je peux'), ('Peut etre', 'Peut etre'), ('Je ne peux pas', 'Je ne peux pas'), ('Conflit', 'Conflit')], max_length=30, null=True),
        ),
    ]
