# Generated by Django 5.0.3 on 2024-05-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_encheres_enthousiasme'),
    ]

    operations = [
        migrations.AddField(
            model_name='soumission',
            name='camera_ready_pdf',
            field=models.FileField(null=True, upload_to='documents/', verbose_name='Camera ready PDF'),
        ),
        migrations.AddField(
            model_name='soumission',
            name='camera_ready_zip',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Camera ready ZIP'),
        ),
    ]
