# Generated by Django 5.0.3 on 2024-05-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_soumission_camera_ready_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soumission',
            name='resume',
            field=models.TextField(max_length=200),
        ),
    ]
