# Generated by Django 5.0.3 on 2024-05-27 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='evenement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.evénement'),
        ),
    ]
